### ISSUE TITLE
script# crash

### ISSUE THREAD

**Issue by pm100** [nikhilk/scriptsharp#121]
reduced to the simplest case

```
using System;
using System.Collections.Generic;
using System.Collections;
using System.Html;
using System.Runtime.CompilerServices;
[assembly: ScriptAssembly("jslate")]
namespace Jslate.Util
{
    public  class Rest
    {
        public static void FFF<TData>( Action<TData> success, Action<object> error)
        {
          // comment out code to actually do stuff

        }
    }
}
```

gives

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ScriptSharp.ScriptModel.SymbolSet.CreateGenericTypeSymbol(TypeSymbol templateType, IList`1 typeArguments)
   at ScriptSharp.ScriptModel.SymbolSet.ResolveType(ParseNode node, ISymbolTable symbolTable, Symbol contextSymbol)
   at ScriptSharp.Compiler.MetadataBuilder.BuildParameter(ParameterNode parameterNode, MethodSymbol methodSymbol)
   at ScriptSharp.Compiler.MetadataBuilder.BuildMethod(MethodDeclarationNode methodNode, TypeSymbol typeSymbol)
   at ScriptSharp.Compiler.MetadataBuilder.BuildMembers(TypeSymbol typeSymbol)
   at ScriptSharp.Compiler.MetadataBuilder.BuildMetadata(ParseNodeList compilationUnits, SymbolSet symbols, CompilerOptions options)
   at ScriptSharp.ScriptCompiler.BuildMetadata()
   at ScriptSharp.ScriptCompiler.Compile(CompilerOptions options)
   at ScriptSharp.Application.Execute(String[] args)
   at ScriptSharp.Application.Main(String[] args)
```

change the method signature to

```
 public static void FFF<TData>( Action<object> success, Action<object> error)
```

all works OK. I have tried to debug using reflector and can see it failing to resolve the second TData symbol. But cant work out why. This signature is common in SS libraries so I must be missing something dumb. If I had the compiler source I could try to fix it. Can another set of eyeballs see anything?

**Comment by nikhilk** [comment]
The compiler doesn't support declaring generic types or methods... only using declared ones.

Here's what you can do however ... you could create an import library (an assembly compiled against the script# mscorlib, but not compiled to javascript by script#) and then reference that in code that does get compiled to javascript.

This level of support needs to be added to script#, but requires a significant change in some of the fundamentals... that work is pending, and as that gets done, will be sharing the sources as well over here.
